### ISSUE TITLE
High CPU usage when using asyncio.open_connection

### ISSUE THREAD

**Issue by saint83** [CabbageDevelopment/qasync#28] opened 2021-02-07 17:53 UTC
Hello all

I am currently hitting some performance issue on a GUI app that uses PyQT5 and asyncio as backend.  
After multiple test I figured out that CPU is 100% used when asyncio.open_connection is used

import asyncio
import sys

from PyQt5.QtWidgets import QApplication
from qasync import QEventLoop

async def start_client():

    reader, writer = await asyncio.open_connection('127.0.0.1', 45678)

    while True:
        print("LOOP")
        await asyncio.sleep(2)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    loop = QEventLoop()
    loop.create_task(start_client())
    loop.run_forever()

When running above code, CPU usage is 100%. If loop = asyncio.get_event_loop() it's used, this issue is not seen

Python 3.9.0
PyQt5           5.15.2
qasync          0.13.0

Do you have any idea why this is happening? 

Thank you

**Comment by saint83** [comment] 2021-02-09 23:19
Downgrading to Python 3.8.6 and this issue is not happening. Seems it's only when Py3.9 it's used

**Comment by ickby** [comment] 2021-02-11 07:19
I have the same issue (see #27 ) and can reproduce your problem. Unfortunately I have no python version < 3.9, maybe you can help me pinpointing the issue? 

when looking at the debug output (add "logging.basicConfig(level=logging.DEBUG)" ) in your snippet the following is spammed:

> DEBUG:qasync._unix._Selector:File 86 ready to write
DEBUG:qasync._QEventLoop:Processing event with key SelectorKey(fileobj=86, fd=86, events=2, data=(None, <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...0.0.1', 8080)>, ('127.0.0.1', 8080))>)) and mask 2
DEBUG:qasync._QEventLoop:Invoking writer callback: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke...0.0.1', 8080)>, ('127.0.0.1', 8080))>

For me it looks strange that _sock_connect_cb is called over and over again, I thougth this is a one-time call function. Could you please check if this spam also happens in python 3.8, or if  _sock_connect_cb is called only once?

**Comment by saint83** [comment] 2021-02-12 12:47
Hi 

Python 3.8.6: 

START
DEBUG:asyncqt._QEventLoop:Adding writer callback for file descriptor 10
DEBUG:asyncqt._QEventLoop:Socket notifier for fd 10 is ready
DEBUG:asyncqt._QEventLoop:Registering callback <bound method _QEventLoop.__notifier_cb_wrapper of <QSelectorEventLoop running=True closed=False debug=False>> to be invoked with arguments ({10: <PyQt5.QtCore.QSocketNotifier object at 0x7fbc7d58f160>}, <PyQt5.QtCore.QSocketNotifier object at 0x7fbc7d58f160>, 10, <bound method BaseSelectorEventLoop._sock_connect_cb of <QSelectorEventLoop running=True closed=False debug=False>>, (<Future pending cb=[BaseSelectorEventLoop._sock_write_done(10)(), <TaskWakeupMethWrapper object at 0x7fbc7d589550>()]>, <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56306), raddr=('127.0.0.1', 45678)>, ('127.0.0.1', 45678))) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 1
DEBUG:asyncqt._SimpleTimer:Timer event on id 1
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle _QEventLoop.__notifier_cb_wrapper({10: <PyQt5.QtCore...x7fbc7d58f160>}, <PyQt5.QtCore...x7fbc7d58f160>, 10, <bound method... debug=False>>, (<Future pendi...c7d589550>()]>, <socket.socke....0.1', 45678)>, ('127.0.0.1', 45678)))>
DEBUG:asyncqt._QEventLoop:Registering callback functools.partial(<bound method BaseSelectorEventLoop._sock_write_done of <QSelectorEventLoop running=True closed=False debug=False>>, 10) to be invoked with arguments (<Future finished result=None cb=[BaseSelectorEventLoop._sock_write_done(10)(), <TaskWakeupMethWrapper object at 0x7fbc7d589550>()]>,) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 2
DEBUG:asyncqt._QEventLoop:Registering callback <TaskWakeupMethWrapper object at 0x7fbc7d589550> to be invoked with arguments (<Future finished result=None cb=[<TaskWakeupMethWrapper object at 0x7fbc7d589550>()]>,) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 3
DEBUG:asyncqt._QEventLoop:Socket notifier for fd 10 is ready
DEBUG:asyncqt._QEventLoop:Registering callback <bound method _QEventLoop.__notifier_cb_wrapper of <QSelectorEventLoop running=True closed=False debug=False>> to be invoked with arguments ({10: <PyQt5.QtCore.QSocketNotifier object at 0x7fbc7d58f160>}, <PyQt5.QtCore.QSocketNotifier object at 0x7fbc7d58f160>, 10, <bound method BaseSelectorEventLoop._sock_connect_cb of <QSelectorEventLoop running=True closed=False debug=False>>, (<Future finished result=None>, <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56306), raddr=('127.0.0.1', 45678)>, ('127.0.0.1', 45678))) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 1
DEBUG:asyncqt._SimpleTimer:Timer event on id 2
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle BaseSelectorEventLoop._sock_write_done(10)(<Future finished result=None>)>
DEBUG:asyncqt._QEventLoop:Removing writer callback for file descriptor 10
DEBUG:asyncqt._SimpleTimer:Timer event on id 3
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle <TaskWakeupMethWrapper object at 0x7fbc7d589550>(<Future finished result=None>)>
DEBUG:asyncqt._QEventLoop:Registering callback <bound method StreamReaderProtocol.connection_made of <asyncio.streams.StreamReaderProtocol object at 0x7fbc7d589310>> to be invoked with arguments (<_SelectorSocketTransport fd=10 read=idle write=<idle, bufsize=0>>,) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 2
DEBUG:asyncqt._QEventLoop:Registering callback <bound method _SelectorTransport._add_reader of <_SelectorSocketTransport fd=10 read=idle write=<idle, bufsize=0>>> to be invoked with arguments (10, <bound method _SelectorSocketTransport._read_ready of <_SelectorSocketTransport fd=10 read=idle write=<idle, bufsize=0>>>) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 4
DEBUG:asyncqt._QEventLoop:Registering callback <function _set_result_unless_cancelled at 0x7fbc7a701c10> to be invoked with arguments (<Future pending>, None) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 5
DEBUG:asyncqt._SimpleTimer:Timer event on id 1
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle _QEventLoop.__notifier_cb_wrapper({}, <PyQt5.QtCore...x7fbc7d58f160>, 10, <bound method... debug=False>>, (<Future finished result=None>, <socket.socke....0.1', 45678)>, ('127.0.0.1', 45678)))>
DEBUG:asyncqt._SimpleTimer:Timer event on id 2
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle StreamReaderProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)>
DEBUG:asyncqt._SimpleTimer:Timer event on id 4
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle _SelectorTransport._add_reader(10, <bound method..., bufsize=0>>>)>
DEBUG:asyncqt._SimpleTimer:Timer event on id 5
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle _set_result_unless_cancelled(<Future pendi...c7d57ffa0>()]>, None) at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py:284>
DEBUG:asyncqt._QEventLoop:Registering callback <TaskWakeupMethWrapper object at 0x7fbc7d57ffa0> to be invoked with arguments (<Future finished result=None cb=[<TaskWakeupMethWrapper object at 0x7fbc7d57ffa0>()]>,) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 4
DEBUG:asyncqt._SimpleTimer:Timer event on id 4
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle <TaskWakeupMethWrapper object at 0x7fbc7d57ffa0>(<Future finished result=None>)>
DEBUG:asyncqt._QEventLoop:Registering callback <function _set_result_unless_cancelled at 0x7fbc7a701c10> to be invoked with arguments (<Future pending>, None) after 2 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 5
LOOP
LOOP
DEBUG:asyncqt._SimpleTimer:Timer event on id 5
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle _set_result_unless_cancelled(<Future pendi...c7d5892b0>()]>, None) at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py:284>
DEBUG:asyncqt._QEventLoop:Registering callback <TaskWakeupMethWrapper object at 0x7fbc7d5892b0> to be invoked with arguments (<Future finished result=None cb=[<TaskWakeupMethWrapper object at 0x7fbc7d5892b0>()]>,) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 4
DEBUG:asyncqt._SimpleTimer:Timer event on id 4
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle <TaskWakeupMethWrapper object at 0x7fbc7d5892b0>(<Future finished result=None>)>
DEBUG:asyncqt._QEventLoop:Registering callback <function _set_result_unless_cancelled at 0x7fbc7a701c10> to be invoked with arguments (<Future pending>, None) after 2 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 5
LOOP
DEBUG:asyncqt._SimpleTimer:Timer event on id 5
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle _set_result_unless_cancelled(<Future pendi...c7d57ffa0>()]>, None) at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py:284>
DEBUG:asyncqt._QEventLoop:Registering callback <TaskWakeupMethWrapper object at 0x7fbc7d57ffa0> to be invoked with arguments (<Future finished result=None cb=[<TaskWakeupMethWrapper object at 0x7fbc7d57ffa0>()]>,) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 4
DEBUG:asyncqt._SimpleTimer:Timer event on id 4
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle <TaskWakeupMethWrapper object at 0x7fbc7d57ffa0>(<Future finished result=None>)>
DEBUG:asyncqt._QEventLoop:Registering callback <function _set_result_unless_cancelled at 0x7fbc7a701c10> to be invoked with arguments (<Future pending>, None) after 2 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 5
DEBUG:asyncqt._SimpleTimer:Timer event on id 5
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle _set_result_unless_cancelled(<Future pendi...c7d5892b0>()]>, None) at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py:284>
DEBUG:asyncqt._QEventLoop:Registering callback <TaskWakeupMethWrapper object at 0x7fbc7d5892b0> to be invoked with arguments (<Future finished result=None cb=[<TaskWakeupMethWrapper object at 0x7fbc7d5892b0>()]>,) after 0 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 4
DEBUG:asyncqt._SimpleTimer:Timer event on id 4
DEBUG:asyncqt._SimpleTimer:Calling handle <Handle <TaskWakeupMethWrapper object at 0x7fbc7d5892b0>(<Future finished result=None>)>
DEBUG:asyncqt._QEventLoop:Registering callback <function _set_result_unless_cancelled at 0x7fbc7a701c10> to be invoked with arguments (<Future pending>, None) after 2 second(s)
DEBUG:asyncqt._SimpleTimer:Registering timer id 5
LOOP
Traceback (most recent call last):
  File "/Users/alexandrudehelean/PycharmProjects/AttServerPy3.8/lib/python3.8/site-packages/asyncqt/__init__.py", line 208, in timerEvent
    def timerEvent(self, event):  # noqa: N802
KeyboardInterrupt

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by saint83** [comment] 2021-02-12 12:50
with py 3.9 it's flooded with: 

EBUG:asyncqt._QEventLoop:Processing event with key SelectorKey(fileobj=16, fd=16, events=3, data=(<Handle _SelectorSocketTransport._read_ready()>, <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke....0.1', 45678)>, ('127.0.0.1', 45678))>)) and mask 2
DEBUG:asyncqt._QEventLoop:Invoking writer callback: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke....0.1', 45678)>, ('127.0.0.1', 45678))>
DEBUG:asyncqt._unix._Selector:File 16 ready to write
DEBUG:asyncqt._QEventLoop:Processing event with key SelectorKey(fileobj=16, fd=16, events=3, data=(<Handle _SelectorSocketTransport._read_ready()>, <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke....0.1', 45678)>, ('127.0.0.1', 45678))>)) and mask 2
DEBUG:asyncqt._QEventLoop:Invoking writer callback: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke....0.1', 45678)>, ('127.0.0.1', 45678))>
DEBUG:asyncqt._unix._Selector:File 16 ready to write
DEBUG:asyncqt._QEventLoop:Processing event with key SelectorKey(fileobj=16, fd=16, events=3, data=(<Handle _SelectorSocketTransport._read_ready()>, <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke....0.1', 45678)>, ('127.0.0.1', 45678))>)) and mask 2
DEBUG:asyncqt._QEventLoop:Invoking writer callback: <Handle BaseSelectorEventLoop._sock_connect_cb(<Future finished result=None>, <socket.socke....0.1', 45678)>, ('127.0.0.1', 45678))>
DEBUG:asyncqt._unix._Selector:File 16 ready to write

**Comment by ickby** [comment] 2021-03-11 07:34
I tried to digg into it, but this is way over my current level of knowledge... Unfortunately I do not have any idea where the problem is yet.

**Comment by occasionallydavid** [comment] 2021-05-18 05:30
It is due to `asyncio.selector_events.BaseSelectorEventLoop._sock_connect`. It is calling `add_writer()` with `_sock_connect_cb`, so far there appears to be no corresponding removal. Double whammy is that `_sock_connect_cb` doesn't crash when called repeatedly, it just ignores the duplicate event. This is terrible design

Still looking

**Comment by occasionallydavid** [comment] 2021-05-18 05:44
It looks like `asyncio.selector_events._add_writer()` is getting called, whereas qasync is only overriding `add_writer()`.

**Comment by occasionallydavid** [comment] 2021-05-18 05:59
Fixed in https://github.com/CabbageDevelopment/qasync/pull/40

**Closed** 2021-08-01 19:55 UTC
